const mensagensBase = [
  'Hoje eu tô mais Odisseu do que gente normal: perdido em mil tarefas, enfrentando ciclopes e prazos, mas toda hora lembro que minha Ítaca é você.',
  'Se a vida é uma Odisseia, você é a ilha onde eu queria ficar preso. Pena que hoje Poseidon me escalou pra plantão de adulto responsável.',
  'Ulisses amarrou-se ao mastro pra não pular no mar. Eu me amarro no trabalho pra não correr direto pro seu abraço agora.',
  'Entre sereias chamando e notificações gritando, a única voz que eu queria ouvir com calma é a sua. O resto é barulho de mar bravo.',
  'Se eu sumir um pouco, não é abandono, é missão épica. A diferença é que, no final, não quero troféu nenhum: só você me esperando em casa.',
  'Tô atravessando um mar de coisa chata, mas o pensamento te coloca no papel de Ítaca com wi-fi e abraço quente. Eu chego aí, herói cansado também precisa de colo.',
  'Hoje minha agenda parece um labirinto de monstros, mas em cada esquina mental tem um “volta pra ela” escrito na parede.',
  'Se Homero narrasse meu dia, ia ser: “E então ele fingiu que estava bem, respondeu e-mails e sentiu saudade dela em silêncio o tempo todo.”',
  'Você é o tipo de porto que faz qualquer tempestade parecer suportável. Só preciso terminar de brigar com os deuses do boleto aqui.',
  'Meu barco tá no meio de ondas altas, mas minha bússola interna continua apontando pro mesmo lugar: seu colo, seu cheiro, sua paz caótica.',
  'Hoje eu tô tipo gato preto: passando rápido pelos cantos, meio invisível, mas mentalmente enroscado no seu colo.',
  'Se eu fosse um gato preto na sua janela agora, já tinha miado até você abrir e me deixar morar no seu travesseiro por alguns minutos.',
  'Entre um problema e outro, eu queria era estar deitado como gato preguiçoso no seu peito, escutando seu coração reclamar da vida comigo.',
  'Tô na correria, mas mentalmente estou naquela cena: eu, você, um gato preto assistindo a gente conversar como se fosse novela.',
  'Se eu aparecer pouco hoje, imagina que virei gatinho arisco: sumo do mundo, mas reapareço pra esfregar carinho na sua perna do nada.',
  'Minha energia social hoje é de gato preto: pouca, seletiva, mas toda sua quando você decide me notar.',
  'Entre azar e sorte, eu escolhi o caminho do gato preto: passo pelo caos inteiro, mas dou um jeito de cair de pé do seu lado no final.',
  'Você é o lar onde até um gato dramático como eu deitaria em paz. Só falta o universo me liberar da rua por cinco minutos.',
  'Se eu pudesse escolher agora, trocava qualquer reunião por ficar enrolado num cobertor, você do lado e um gato preto julgando nossas decisões.',
  'Hoje eu tô miando internamente, pedindo colo, mas o mundo só escuta digitação. No fim do dia, quero ser o seu gato cansado favorito.',
  'Tem dia que eu pareço vampiro: sumo do sol, vivo na tela e durmo pouco. Mas minha parte preferida ainda é te imaginar na madrugada comigo.',
  'Se eu fosse vampiro, te chamaria pra viver uma eternidade de conversas estranhas e cafés noturnos. Por enquanto, é só mais um dia cansado mesmo.',
  'Desculpa o sumiço, é que acordei no modo “criatura da noite”: funcionamento limitado à luz baixa e mensagens atrasadas.',
  'Tô mais pálido que vampiro de filme e com a mesma vontade de morder a vida de raiva. A diferença é que por você eu sempre amoleço.',
  'Se você me visse agora, ia achar que eu saí direto de um castelo gótico: olheiras profundas, roupa amassada, mas ainda disposto a te adorar em silêncio.',
  'Entre sugar energia de problema e sugar sua atenção, prefiro a segunda opção. Pena que hoje o sistema me escalou pro lado errado.',
  'Hoje eu tô com vibe de vampira romântica: dramático, meio sombrio, mas completamente obcecado por uma pessoa específica. Spoiler: é você.',
  'Se a madrugada nos juntasse hoje, eu faria pacto de eternidade só de ficar conversando até o sol nascer e destruir nosso sono juntos.',
  'Talvez eu não esteja brilhando como vampiro de filme adolescente, mas é pensar em você que me lembra que ainda existe luz nessa bagunça.',
  'Quando tudo fica pesado, eu imagino a cena: eu bati na sua porta de madrugada, vampiro cansado pedindo abrigo afetivo por algumas horas.',
  'Se meu dia tivesse trilha sonora, hoje seria Melanie Martinez: estética fofa, letra caótica e um humor meio quebrado, tipo eu tentando funcionar.',
  'Às vezes eu me sinto personagem de música da Melanie: o mundo cobrando ser perfeito e eu só querendo deitar no chão e rir do próprio drama contigo.',
  'Se a gente tivesse um clipe juntos, seria você segurando minha mão enquanto tudo desaba em volta, mas a estética continua impecável.',
  'Hoje eu tô versão “doll quebrada”: funcionando pela metade, mas com vontade de ser gentil com você do jeito que eu consigo.',
  'Pensa em mim como música triste com batida bonita: cansado por dentro, mas ainda dançando meio torto por saber que tenho você na história.',
  'Se eu pudesse te mandar um verso agora, seria daqueles que parecem fofos mas escondem trauma. A diferença é que com você dá vontade de curar, não só rimar.',
  'Minha cabeça hoje é um álbum inteiro de Melanie Martinez: tem crítica, caos e vulnerabilidade demais. Mas, no meio, sempre aparece uma faixa chamada “você”.',
  'Eu sei que pareço sumir, mas é só meu cérebro editando o clipe. No corte final, você sempre está nas melhores cenas.',
  'Se você for o refrão, prometo que mesmo cansado eu volto pra repetir mil vezes até decorar de cor.',
  'Se a vida é RPG de Ordem Paranormal, hoje eu tô claramente com sanidade baixa e ficha toda rabiscada, mas ainda segurando o amuleto com seu nome.',
  'Minha roleplay mental é simples: eu de investigador ferrado, você de ponto seguro no fim da sessão, onde eu posso largar o fardo por uns minutos.',
  'Se Cellbit narrasse meu dia, teria teste de coragem a cada mensagem ignorada. E o sucesso crítico sempre seria te ver rindo de algo meu.',
  'O mundo hoje tá cheio de entidade estranha, mas o único pacto que eu realmente quero é com a sua paz perto de mim.',
  'Tô fugindo de assombração real (responsabilidade), mas a única presença que eu queria ser perseguido é pela ideia de você aqui do lado.',
  'Se eu tomar dano de sanidade hoje, é pelo excesso de tarefa, não por você. Você é o único buff que ainda segura meus pontos de vida.',
  'Imagina a cena: depois de uma sessão caótica, meu personagem exausto encontra você e finalmente consegue rolar um descanso longo de verdade.',
  'Às vezes eu sinto que minha vida é ficha mal montada, mas quando você entra na cena parece que o mestre decidiu ser gentil comigo.',
  'Se esse dia fosse uma mesa de Ordem, você seria o NPC raro que transforma lugar amaldiçoado em refúgio improvável.',
  'No meio das anomalias todas, a coisa mais estranha ainda é alguém como você ter paciência com alguém como eu.',
  'Toda vez que eu penso em desistir do turno, lembro que em alguma linha da história ainda tem “ele volta pra ela cansado, mas feliz de ter pra onde ir”.',
  'Se minha vida é um continente cheio de caos, você é a cidadezinha estranha que parece amaldiçoada por fora, mas por dentro é o único lugar que faz sentido.',
  'Hoje eu tô jogando no modo difícil, mas o verdadeiro final secreto é simples: terminar o dia com uma mensagem sua e um pouco de paz dividida.',
  'Se os deuses estão me testando, claramente não viram o tanto de XP que ganho só por continuar gostando de você mesmo nos dias ruins.',
  'No mapa mental do meu dia, você é o ponto de fast travel que ainda não desbloqueei fisicamente, mas visito em pensamento o tempo todo.',
  'Entre mares gregos, gatos pretos, vampiras cansadas e trilhas de terror, a única constante é: no fim da cena, eu ainda tô te escolhendo.',
  'Talvez eu esteja vivendo vinte enredos ao mesmo tempo, mas em todos eles tem uma versão de mim mandando mensagem atrasada dizendo “eu pensei em você”.',
  'Se eu desapareço por algumas horas, não é bug de roteiro, é side quest obrigatória. A missão principal continua sendo voltar pra você.',
  'Você é meu plot twist favorito: no meio de todas as histórias estranhas, foi a única que fez meu personagem querer um final decente.',
  'Quando esse episódio terminar, eu não quero créditos subindo. Quero só uma cena simples: eu, você, silêncio confortável e nenhum monstro à vista.',
  'Eu sei que às vezes pareço mais personagem do que pessoa real, mas o sentimento por você é a parte mais sincera do meu roteiro.',
  'Se minha mente é um compilado de fandoms caóticos, você é o crossover que eu nunca soube que precisava, mas agora não quero perder.',
  'Entre Odisseu, gatos pretos, vampiras dramáticas, clipes da Melanie e sessões de Ordem, a única constante é você sendo meu ponto de retorno.',
  'Hoje eu não tenho grandes discursos, só uma certeza meio boba: em qualquer universo estranho, eu ainda ia achar um jeito de esbarrar em você.',
  'Talvez eu esteja exagerando, mas se existe de fato um mestre narrando tudo isso, ele claramente decidiu shippar a gente e eu só tô seguindo o roteiro.',
  'Se isso aqui fosse final de temporada, meu cliffhanger ideal seria simples: “ele volta cansado, manda mensagem pra ela e, pela primeira vez no dia, sorri de verdade”.',
  'Enquanto o mundo pede que eu seja herói, eu tô aqui feliz em ser só seu personagem falho favorito, contanto que ainda tenha um pouco de espaço na sua história.',
  'Mesmo quando tudo parece bugado, o único glitch que eu nunca quero consertar é esse: meu pensamento travando em você no meio de qualquer caos.',
  'Eu posso estar enfrentando monstros, chefes de fase e deadlines, mas a parte que mais me motiva ainda é imaginar você dizendo “fica mais um pouco”.',
  'Se um dia alguém revisitar esse capítulo da minha vida, espero que perceba: por trás de todo o drama, a única constante bonita era o jeito que eu pensava em você.',
  'Hoje a rede aqui tá igual minha cabeça: instável. Se cair do nada, saiba que minha conexão com você continua em uptime máximo.',
  'Tô roteando atenção entre mil tarefas, mas seu nome sempre fura o firewall e chega em broadcast direto no meu peito.',
  'Se meu coração fosse servidor, você seria acesso prioritário. O resto do mundo que lide com latência e erro 503.',
  'Entre pacotes perdidos e mensagens atrasadas, a única coisa que não sofre delay é a vontade de te mandar um “sdds” honesto.',
  'Meu dia hoje tá igual Wi‑Fi ruim: cai toda hora. Mas quando penso em você, parece que tudo entra em fibra ótica emocional.',
  'Se eu pudesse configurar a vida, colocava você como gateway padrão: qualquer caminho complicado acabaria direcionando pra você.',
  'A CPU tá a 100%, a RAM quase estourando, mas ainda reservo uns ciclos só pra imaginar você sorrindo quando ler minhas mensagens.',
  'Tem bug que derruba sistema, e tem você, que derruba minhas defesas. A diferença é que eu nunca quero aplicar patch pra isso.',
  'Se meu coração tivesse log, cada linha hoje diria "warning: saudade alta" toda vez que seu nome aparece na memória.',
  'Tô em modo debug da vida, mas o único breakpoint que eu realmente respeito é quando penso em você e paro pra respirar.',
  'Entre exception e stack trace, o único erro que eu aceito repetir é cair de novo na ideia de você.',
  'Se eu fosse API, você teria token vitalício com acesso total às melhores partes de mim.',
  'Hoje o servidor principal aqui dentro tá sobrecarregado, mas seu ping emocional continua em 0ms.',
  'Se o amor tivesse ping, o meu com você não passava nem perto de time‑out, mesmo com o mundo lagado.',
  'Tô fazendo load balancing entre trabalho, problemas e você. Spoiler: você sempre recebe mais requisição de carinho.',
  'Se minha rotina fosse cluster, você seria o nó que nunca pode cair. O resto a gente reinicia depois.',
  'Tem dia que eu respondo mais requisição HTTP do que mensagem sua. Resultado: sistema funcionando, coração com erro 404 de abraço.',
  'Hoje eu tô rodando em modo manutenção, mas se você chamar, eu subo o serviço de atenção exclusiva rapidinho.',
  'Se o mundo está em broadcast de caos, eu queria te mandar um unicast de paz, direto do meu peito pro seu.',
  'Minha mente tá lotada de threads, mas a única que eu não deixo morrer é a que pensa em você no background.',
  'Entre pacotes indo e vindo, o único dado que eu não quero perder é o fato de que você me faz querer continuar online.',
  'Se a gente tivesse um protocolo próprio, seria simples: pouca formalidade, muito sarcasmo e envio ilimitado de afeto.',
  'Tô roteando problemas o dia inteiro, mas a rota mais estável que eu conheço ainda leva pro seu número.',
  'Hoje até o DNS da minha cabeça demora pra resolver qualquer coisa, menos quando alguém fala de você.',
  'Se você fosse rede cabeada, eu desligava o Wi‑Fi da vida inteira só pra ficar conectado em você sem interferência.',
  'Às vezes eu funciono como servidor sem monitoria: ninguém vê o quanto tô sobrecarregado, mas você sempre percebe algum alerta em mim.',
  'Meu humor hoje é tipo porta fechada em firewall: seletivo demais. Mas pra você sempre tem regra de entrada liberada.',
  'Entre porta 80 e 443, a única conexão segura que eu realmente confio é a que eu sinto quando você me responde com carinho.',
  'Se eu pudesse dar um `ping` no futuro, gostaria só de confirmar que, em alguma versão dele, a gente deu certo.',
  'Hoje eu tô rodando script de sobrevivência, mas a função principal ainda é voltar inteiro pra você no fim do dia.',
  'Às vezes eu crasho sem aviso, mas é pensar em você que faz meu sistema reiniciar em modo menos desesperado.',
  'Se as horas fossem requests, eu já estaria em rate limit. Mas pra você eu sempre tento dar um jeito de liberar mais uma.',
  'Tô em modo CLI com a vida: comandos rápidos, pouco visual. Mas quando penso em você, parece que volto pra interface gráfica bonita.',
  'Meu pacote emocional hoje vem com latência alta, mas a payload é simples: sinto sua falta mais do que demonstro.',
  'Se cada sensação fosse um pacote TCP, o meu por você teria triple handshake infinito só pra garantir que não se perde.',
  'Entre protocolos e padrões, o único que eu queria quebrar é o de fingir que tá tudo bem sem você por perto.',
  'Hoje o log do meu dia tem muito erro, mas também tem linhas onde seu nome aparece como info importante.',
  'Se eu pudesse dar um `traceroute` no motivo da minha teimosia, aposto que a rota final daria no seu sorriso.',
  'Entre stack overflow de problema e falta de memória pra descanso, você ainda é meu garbage collector emocional favorito.',
  'Se a vida insistir em dar kernel panic, eu só peço pra, antes disso, ter mais alguns reboots ao seu lado.',
  'Tô quase dando Ctrl+C na semana, mas aí lembro que ainda tem a chance de te ver e viro Ctrl+S pra salvar o pouco de sanidade que sobrou.',
  'Se amor fosse protocolo, o nosso suportaria perda de pacotes, delay e até rede instável, mas nunca falta de sinceridade.',
  'Eu sei que o mundo quer que eu seja sistemático e eficiente, mas perto de você eu gosto mesmo é de virar bug feliz.',
  'Talvez eu seja só mais um dev cansado no planeta, mas quando penso em você, meu coração faz deploy de esperança sem rollback.'
];

const piadas = [
  // Irônicas (secas)
  'Ironia é eu estar atolado de coisa pra fazer e ainda assim lendo essa mensagem. Se isso não é dedicação, é teimosia. 😏',
  'Disseram que o tempo cura tudo, mas até agora ele só piorou minha agenda e aumentou o número de mensagens inúteis. ⏰',
  'Tô tão ocupado que, se aparecer mais uma notificação sem emergência, vou começar a tratar como bug crítico. Inclusive essa. 🎟️',
  'Meu nível de produtividade hoje: 10% trabalho, 90% desviando de conversa desnecessária. �',
  'Ironia do dia: quem tá atolado de tarefa sou eu, mas quem faz drama é você. Matemática criativa. ☕',
  'Me falaram “elimine distrações”, mas esqueceram de criar o botão “silenciar gente insistente”. �',
  'Eu ia descansar, mas o universo decidiu testar minha paciência com mais uma mensagem. Universo com humor duvidoso. 😂',
  'Tô tão cheio de coisa que, se abrir minha mente agora, tem trabalho, cobrança e você aparecendo como pop-up chato. 📺',
  'Agenda cheia, paciência vazia. E adivinha onde essa conversa entra. 😌',
  'A vida pediu foco, eu aceitei. Você entrou na chamada sem ser convidado(a). 🧠',

  // Programação (sarcásticas, sem romance)
  'Se eu fosse um código, você seria aquele comentário inútil que ninguém sabe quem escreveu, mas todo mundo xinga. 💻',
  'Nossa conversa parece código legado: ninguém entende por que ainda existe, mas todo mundo tem medo de apagar de vez. 😏',
  'Se essa interação fosse função, seria recursiva sem retorno: só consome recurso e não entrega nada de útil. 🌀',
  'Você é tipo variável global: aparece em tudo quanto é lugar sem ninguém pedir e ainda causa conflito. 🧠',
  'Meu cérebro é servidor em produção: sobrecarregado. Sua mensagem é aquela requisição desnecessária em horário de pico. 🖥️',
  'Se cada texto seu fosse log, o sistema já tinha caído de tanto warning inútil. 🧾',
  'Seu timing é tipo deploy em sexta à noite: sempre na pior hora possível e com grande chance de dar problema. 🚀',
  'Essa conversa é igual sistema sem documentação: começou não sei como e ninguém sabe como manter isso sem dor de cabeça. 😌',
  'Você é o bug que eu ainda não abri issue só porque tô ocupado apagando incêndio mais importante. 🐞',
  'Se insistência fosse exceção, você vivia dando `throw` em produção. 💻',
  'Tô em modo async/await com tudo, menos com drama. Esse eu dou `cancel()` na hora. ⏳',
  'Meu dia é uma API lotada de requisição inútil e essa conversa acabou de ganhar status 429: too many requests. 📡',
  'Se atenção fosse pull request, o seu ficaria eternamente em “changes requested”. 🔒',
  'Tem variável booleana aqui chamada `precisoDessaConversa` e ela insiste em ser `false`. 💚',
  'Se eu for debugar isso aqui, o console vai mostrar só “porque eu ainda tô lendo isso?”. 🧑‍💻',

  // Odisseia / Odisseu (mais ácidas)
  'Odisseu demorou anos pra voltar pra casa. Eu demoro minutos pra responder e já tratam como tragédia épica. Respira, Homero. ⛵',
  'Se eu fosse Odisseu, você seria o mar: barulho constante, dificuldade garantida e zero aviso de tempestade. 🌊',
  'As sereias cantavam pra Odisseu. No meu caso, o canto é notificação do WhatsApp tocando na pior hora. 🎶',
  'Nem todas as viagens de Odisseu cansam tanto quanto um dia inteiro respondendo mensagem fora de contexto. 🗺️',
  'Ulisses se amarrou ao mastro pra não ouvir as sereias. Eu devia me amarrar ao modo avião pra não cair em conversa aleatória. 😅',
  'Ítaca era o destino de Odisseu. O meu é só tentar chegar no fim do dia sem mais um textão desnecessário. 🏝️',
  'Nem ciclope, nem Poseidon, nem tempestade: o verdadeiro desafio é lidar com gente que manda “oi” sem assunto. 🌩️',
  'Odisseu enfrentou monstros mitológicos. Eu enfrento prazos, boletos e notificação sua. ⚔️☕',
  'Se Homero escrevesse sobre mim, o título seria “A arte de tentar trabalhar enquanto o WhatsApp insiste em atrapalhar”. 📜',
  'Odisseu tinha o mar inteiro contra ele; eu tenho o relógio, o trabalho e esse chat infinito. Empate técnico. ⏰',

  // Animes (sarcasmo leve/ácido)
  'Se isso aqui fosse um anime, você seria o personagem caótico que aparece só pra atrasar o arco principal. 🎬',
  'Essa conversa é tipo shonen infinito: muito episódio, pouco progresso real e só desgaste do protagonista. 💥',
  'Nosso enredo parece slice of life ruim: nada acontece, mas a sensação de vergonha alheia aumenta a cada cena. 🍃',
  'Se eu tivesse um poder de anime, seria pausar o tempo só pra ignorar mensagens que chegam na hora errada. ⏸️',
  'Você é tipo opening grudenta: repete tanto que enjoa, mas continua tocando. 🎵',
  'Se eu fosse protagonista, você seria o personagem que o público implora pra ter menos tempo de tela. 😂',
  'Meu humor hoje é tipo protagonista de shoujo sem dormir: qualquer coisa vira drama desnecessário. 💗',
  'Com você, até filler parece episódio arrastado: longo demais pra pouca história. 🎞️',
  'Essa conversa é tipo final de temporada ruim: você espera algo grande, recebe mais do mesmo. 📺',
  'Se fosse anime, esse arco já teria sido dropado na metade por falta de desenvolvimento. ♾️',
  'Tem coisa que parece fanservice, mas aqui é só a vida jogando plot desnecessário na minha tela. ✨',
  'Se meu dia fosse arco de batalha, essa notificação seria o miniboss irritante que aparece só pra atrasar a missão principal. ⚡',
  'Entre vilões e plot twists, a verdadeira ameaça à minha sanidade é esse chat infinito. 📚',
  'Se eu sumo, é porque tô em treinamento longe da tela, tentando aumentar resistência a conversa aleatória. 💪',
  'Se isso aqui fosse anime, esse episódio já tinha sido pulado no botão “pular intro e cena”. 📲',

  // Extras misturadas (mais secas)
  'Tô tão ocupado que, se a vida fosse RPG, eu estaria em missão importante e essa conversa seria aquele NPC chato repetindo falas inúteis. 🎮',
  'Se os dias fossem fases de jogo, hoje eu tô na fase difícil e você clicando em “repetir” só pra ver se eu desisto. 💾',
  'Meu humor hoje tá tipo console travado: qualquer comando errado e eu desligo. 🛠️',
  'Se eu pudesse usar fast travel, ia direto pra parte em que o celular para de fazer barulho. 🗺️',
  'Entre bugs, crashes e reboots, essa conversa é aquele erro que insiste em aparecer no log sem motivo aparente. 💡',
  'Dizem que ninguém é perfeito, mas algumas conversas chegam bem perto da definição de falha de sistema. 😌',
  'Se meu dia tivesse trilha sonora, agora estaria tocando música de chefão. E adivinha quem entrou na arena sem convite. 🎶',
  'Tô em modo “ocupado”, mas aparentemente isso é interpretado como “mande mais mensagem, por favor”. 💚',
  'A vida tá em modo difícil e você desbloqueou a conquista secreta de “interrupção nível máximo”. 🏆',
  'Se existir multiverso, em todos eles eu provavelmente ainda tô ocupado demais pra ficar lendo mensagem desnecessária. 🌌',
  'Entre todas as notificações, a única que mais me atrapalha continua sendo essa conversa. Parabéns pelo destaque. 🔔',
  'Se chat inútil fosse bug, isso aqui já teria derrubado o sistema inteiro. 🐛',
  'Meu foco hoje tá dividido entre trabalho, problema e distração. Adivinha em qual categoria essa conversa entrou. ✨',
  'Talvez eu esteja sumido, mas é só porque o modo “sobreviver ao dia” não vem com suporte a diálogo infinito. 💞'
];

const motivacionaisSarc = [
  'Vai dar certo? Provavelmente não do jeito que você imagina, mas pelo menos rende história pra contar.',
  'Você não está atrasado, o mundo é que é otimista demais com prazos irreais.',
  'A boa notícia é que você ainda tá tentando. A ruim é que o universo continua em modo difícil.',
  'Uma hora tudo se ajeita. Geralmente depois de você apanhar um pouco mais do que gostaria.',
  'Seu esforço não é em vão. Ele só demora pra aparecer no placar, tipo jogo mal balanceado.',
  'Levanta a cabeça. Não que resolva, mas pelo menos a postura melhora.',
  'Respira fundo. Pior que tá, sempre pode ficar, então aproveita o “ainda não”.',
  'Você já sobreviveu a todos os dias ruins até hoje. Estatística tá do seu lado, por incrível que pareça.',
  'O plano pode não estar funcionando, mas olha pelo lado bom: agora você sabe o que não fazer de novo.',
  'Às vezes o universo só tá te testando. Outras vezes ele só tá distraído mesmo.',
  'Você não é fracasso, só está em versão beta ainda. Tem bug, mas funciona.',
  'Metade do caminho é tentar. A outra metade é fingir que sabe o que tá fazendo até dar certo.',
  'Se nada fizer sentido, finge que é fase experimental da sua biografia.',
  'O famoso “vai dar tudo certo” na verdade significa “vai dar alguma coisa, depois a gente vê o que faz”.',
  'Você não precisa ter tudo sob controle. Até porque ninguém tem, só fingem melhor.',
  'Tem dia que o máximo que dá pra fazer é existir. Já é trabalho em tempo integral.',
  'Você não tá perdido, só tá fazendo um caminho mais longo do que o necessário. Acontece.',
  'Não é que você esteja sem forças, é que viver no modo difícil cansa mesmo.',
  'Às vezes o melhor que dá pra fazer é não desistir hoje. Amanhã você reconsidera.',
  'Se a vida fechar uma porta, verifica se não era só falta de lubrificação emocional.',
  'Seu caos interno não te define. Ele só deixa tudo mais interessante pros bastidores.',
  'Você já fez coisa difícil antes. Essa é só mais uma rodada de sofrimento com estilo.',
  'Pode não parecer, mas você está avançando. Lento, tropeçando, mas avançando.',
  'Nem todo cansaço é fraqueza. Às vezes é só prova de que você tá carregando coisa demais sozinho(a).',
  'Se o mundo não te der um motivo pra sorrir, dá uma risada de nervoso mesmo. Conta também.',
  'Você não precisa ser inspiração de ninguém hoje. Só precisa sobreviver sem explodir.',
  'Já deu certo antes quando parecia que não ia. A chance não é grande, mas existe.',
  'Tá confuso(a)? Normal. Quem diz que sabe exatamente o que tá fazendo tá mentindo.',
  'Você não está parado, está processando. Igual computador velho, demora, mas vai.',
  'Nem sempre o que você queria é o que você precisava. Incomodar faz parte do pacote de crescimento.'
];

const destinos = [
  'Vai dar bom. Não muito, mas o suficiente pra você não desistir ainda.',
  'Vai dar ruim, mas você vai aprender. Pelo menos é conteúdo pra terapia.',
  'Talvez dê certo. Talvez não. Mas você já tá no meio, então segue.',
  'Honestamente? As chances não são incríveis, mas já vi coisa pior funcionar.',
  'Não conta muito com isso, mas também não precisa entrar em pânico ainda.',
  'Se fosse pra dar muito certo, não estaria parecendo tão confuso assim.',
  'Vai depender menos do destino e mais do tanto de caos que você aguenta.',
  'Pode tentar. O máximo que acontece é dar errado de um jeito novo.',
  'Isso aí tem cara de “vai dar trabalho antes de dar resultado”.',
  'Se você espera um milagre, talvez esteja no grupo errado. Mas tenta, vai.',
  'O universo não prometeu facilidade, só enredo. E isso você tá tendo.',
  'Se der certo, ótimo. Se der errado, você ganha experiência de personagem cansado.',
  'Probabilidade moderada de “funciona mais ou menos e você se acostuma”.',
  'Tem 50% de chance: ou dá certo, ou você finge que nunca tentou.',
  'Dá pra ir. Só não esquece de levar expectativa baixa pra não se decepcionar tanto.',
  'Destino aqui diz: pode ir, mas não venha reclamar depois sem café.',
  'Se você tá perguntando isso pro bot, a resposta já é “cautela”.',
  'Talvez o problema não seja o destino, sejam as suas escolhas anteriores.',
  'Vai dar certo do jeito torto, atrasado e improvisado que a vida gosta.',
  'Isso cheira a encrenca, mas também a história boa. Você decide o que pesa mais.'
];

const euTeAmoRespostas = [
  'Eu te amo de um jeito tão bugado e bonito que nem se eu reescrevesse o código do universo dava pra explicar direito.',
  'Eu te amo em todos os universos possíveis, até nos que eu tô cansado demais pra falar, mas nunca pra sentir.',
  'Eu te amo em silêncio, em alto e bom som, em mensagem atrasada e em pensamento de madrugada.',
  'Te amo mais do que Wi‑Fi estável, mais do que café quente e mais do que qualquer final feliz bem escrito.',
  'Eu te amo até nos dias em que eu tô um caos completo, principalmente neles, porque é quando mais preciso de você.',
  'Te amo tanto que, se a vida travar, eu dou reboot segurando sua mão e tentando de novo.',
  'Eu te amo no modo online, offline, ocupado, ausente e principalmente no modo “vem aqui e fica comigo”.',
  'Te amo num nível que nem debugger encontra o limite, só mais camadas de sentimento esquisito e sincero.',
  'Eu te amo hoje, amanhã e em todos os dias bugados que ainda vêm por aí. E isso não tem rollback.',
  'Te amo mais do que qualquer plot twist, porque você é a única parte da história que eu não quero perder.'
];

module.exports = {
  mensagensBase,
  piadas,
  motivacionaisSarc,
  destinos,
  euTeAmoRespostas
};
